// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayWeb.Infrastructure;

namespace PayWeb.Migrations
{
    [DbContext(typeof(PayWebContext))]
    partial class PayWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PayWeb.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AdminAx")
                        .HasColumnType("bit");

                    b.Property<string>("Ano_Semana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodEmpresaInt")
                        .HasColumnType("int");

                    b.Property<string>("Cod_Alterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cod_Empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cod_Personal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicial")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mes_Proceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PassWord");

                    b.Property<string>("Proceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserId");

                    b.Property<string>("planilla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PayWeb.Models.AjustePartida", b =>
                {
                    b.Property<int>("CodAjuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodTipoPlanilla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodAjuste");

                    b.ToTable("AjustePartida");
                });

            modelBuilder.Entity("PayWeb.Models.Asistencia", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodPersonal")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("AlmuerzoEntrada")
                        .HasColumnType("Datetime");

                    b.Property<DateTime?>("AlmuerzoSalida")
                        .HasColumnType("Datetime");

                    b.Property<DateTime?>("Entrada")
                        .HasColumnType("Datetime");

                    b.Property<decimal?>("HorasAusencias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HorasSinJustificar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Migrado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("Datetime");

                    b.Property<decimal?>("TotalHorasExtras")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("fecha_Actualizacion")
                        .HasColumnType("Datetime");

                    b.Property<decimal?>("hora")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("usuario_Actualizacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("usuario_Creacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CodEmpresa", "CodPersonal", "Fecha");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("PayWeb.Models.BonoExenta", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaSemana")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodIntegrado")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BonoSA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BonoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CodTipoPlanilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Eficiencia")
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Migrado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodEmpresa", "FechaSemana", "CodIntegrado");

                    b.ToTable("BonoExenta");
                });

            modelBuilder.Entity("PayWeb.Models.ConceptoCoo", b =>
                {
                    b.Property<string>("cod_Empresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("concepto")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("cod_tip_planilla")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("cod_Empresa", "concepto", "cod_tip_planilla");

                    b.ToTable("ConceptoCoo");
                });

            modelBuilder.Entity("PayWeb.Models.Conceptos", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Concepto")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("cod_tip_planilla")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("porcentaje")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("CodEmpresa", "Concepto", "cod_tip_planilla");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("PayWeb.Models.Conceptos_Alimenticios", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodPersonal")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<string>("Concepto")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Migrado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("fecha_Actualizacion")
                        .HasColumnType("Datetime");

                    b.Property<string>("usuario_Actualizacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("usuario_Creacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CodEmpresa", "CodPersonal", "Fecha", "Concepto");

                    b.ToTable("Conceptos_Alimenticios");
                });

            modelBuilder.Entity("PayWeb.Models.Conexiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AXServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegradoServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conexiones");
                });

            modelBuilder.Entity("PayWeb.Models.ControlEmpresas", b =>
                {
                    b.Property<int>("idControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cod_Empresa_Integrado")
                        .HasColumnType("int");

                    b.Property<string>("Cod_Empresa_PayRoll")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("idControl");

                    b.ToTable("ControlEmpresas");
                });

            modelBuilder.Entity("PayWeb.Models.ControlPartidas", b =>
                {
                    b.Property<int>("CodControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CodFactor")
                        .HasColumnType("int");

                    b.Property<string>("CodProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoPlanilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodControl");

                    b.HasIndex("CodFactor");

                    b.ToTable("ControlPartidas");
                });

            modelBuilder.Entity("PayWeb.Models.ControlPlanillasMigradas", b =>
                {
                    b.Property<int>("CodEmpresaInt")
                        .HasColumnType("int");

                    b.Property<string>("CodEmpresaPay")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodTipoPlanillaInt")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CodTipoPlanillaPay")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("CodSatelite")
                        .HasColumnType("int");

                    b.Property<bool>("MigradoPay")
                        .HasColumnType("bit");

                    b.HasKey("CodEmpresaInt", "CodEmpresaPay", "CodTipoPlanillaInt", "CodTipoPlanillaPay", "CodSatelite");

                    b.HasIndex("CodSatelite");

                    b.ToTable("ControlPlanillasMigradas");
                });

            modelBuilder.Entity("PayWeb.Models.Control_Bancos", b =>
                {
                    b.Property<int>("idControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cod_Empresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("Cod_Bnc_Aux_Int")
                        .HasColumnType("int");

                    b.Property<string>("Cod_Bnc_Aux_PR")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.HasKey("idControl", "Cod_Empresa");

                    b.ToTable("Control_Bancos");
                });

            modelBuilder.Entity("PayWeb.Models.Control_Ciudades", b =>
                {
                    b.Property<int>("idControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cod_Empresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("AdpCodCiu_Aux_Int")
                        .HasColumnType("int");

                    b.Property<string>("Cod_Ciu_Aux_PR")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Cod_Depar_Aux")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("idControl", "Cod_Empresa");

                    b.ToTable("Control_Ciudades");
                });

            modelBuilder.Entity("PayWeb.Models.Control_Conceptos", b =>
                {
                    b.Property<int>("idControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cod_Empresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Cod_Concepto_Integrado")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Cod_Concepto_PayRoll")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("idControl", "Cod_Empresa");

                    b.ToTable("Control_Conceptos");
                });

            modelBuilder.Entity("PayWeb.Models.Control_Planillas", b =>
                {
                    b.Property<int>("idControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Cod_Frm_Pag")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<int>("Cod_Tip_Pla_Integrado")
                        .HasColumnType("int");

                    b.Property<string>("Cod_Tip_Pla_PayRoll")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("idControl", "CodEmpresa");

                    b.ToTable("Control_Planillas");
                });

            modelBuilder.Entity("PayWeb.Models.Control_Semanas", b =>
                {
                    b.Property<int>("idControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Ano_Proceso")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Cod_Proc_Gral")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Cod_Tip_Pla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("FechaFinal")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaProceso")
                        .HasColumnType("datetime");

                    b.Property<string>("Mes_Proceso")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("PlsNumSem")
                        .HasColumnType("int");

                    b.HasKey("idControl", "CodEmpresa");

                    b.ToTable("Control_Semanas");
                });

            modelBuilder.Entity("PayWeb.Models.DescripcionPartida", b =>
                {
                    b.Property<string>("CodTipoPlanilla")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DesTipoPlanilla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodTipoPlanilla");

                    b.ToTable("DescripcionPartida");
                });

            modelBuilder.Entity("PayWeb.Models.DetalleCooperativa", b =>
                {
                    b.Property<int>("idDetCoop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Ano_Proceso")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CodConcepto")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CodPersonal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Cod_Proc_Gral")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Cod_Tip_Pla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Mes_Proceso")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MigradoInt")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(7,3)");

                    b.HasKey("idDetCoop", "CodEmpresa");

                    b.ToTable("DetalleCooperativa");
                });

            modelBuilder.Entity("PayWeb.Models.DetalleDiaParametros", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("DetalleParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParametroId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoDetalleId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("CodEmpresa", "DetalleParametroId");

                    b.ToTable("DetalleDiaParametros");
                });

            modelBuilder.Entity("PayWeb.Models.Factor", b =>
                {
                    b.Property<int>("CodFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DescFactor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodFactor");

                    b.ToTable("Factor");
                });

            modelBuilder.Entity("PayWeb.Models.FactorDetalle", b =>
                {
                    b.Property<int>("CodDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CodFactor")
                        .HasColumnType("int");

                    b.Property<int>("TipoPartida")
                        .HasColumnType("int");

                    b.HasKey("CodDetalle");

                    b.HasIndex("CodFactor");

                    b.ToTable("FactorDetalle");
                });

            modelBuilder.Entity("PayWeb.Models.HistorialPrestamos", b =>
                {
                    b.Property<int>("noPrestamo")
                        .HasColumnType("int");

                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CodPersonal")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("CodRegistro")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("CuotaNivelada")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("TotalPrestamo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ValorInteres")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("noPrestamo", "CodEmpresa", "CodPersonal", "CodRegistro");

                    b.ToTable("HistorialPrestamos");
                });

            modelBuilder.Entity("PayWeb.Models.Historial_Saldos_Prestamos", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CodPersonal")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("CodRegistro")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("Cuota_Manual")
                        .HasColumnType("decimal(10,3)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero_Cuotas")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo_Acumulado")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("CodEmpresa", "CodPersonal", "CodRegistro");

                    b.ToTable("Historial_Saldos_Prestamos");
                });

            modelBuilder.Entity("PayWeb.Models.HorasExtra", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodPersonal")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<string>("Concepto")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("HorasExtras")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Migrado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("fecha_Actualizacion")
                        .HasColumnType("Datetime");

                    b.Property<string>("usuario_Actualizacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("usuario_Creacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CodEmpresa", "CodPersonal", "Fecha", "Concepto");

                    b.ToTable("HorasExtra");
                });

            modelBuilder.Entity("PayWeb.Models.Migracion_Masiva", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("identidad")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("Migracion_Masiva");
                });

            modelBuilder.Entity("PayWeb.Models.Moneda", b =>
                {
                    b.Property<string>("CodMoneda")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CodMoneda");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("PayWeb.Models.Parametros", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("horaEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("horaSalida")
                        .HasColumnType("datetime");

                    b.HasKey("ParametroId", "CodEmpresa");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("PayWeb.Models.Partida", b =>
                {
                    b.Property<int>("CodPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoPlanilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoPartida")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CodPartida");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("PayWeb.Models.PartidaDetalle", b =>
                {
                    b.Property<int>("CodPartidaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CodPartida")
                        .HasColumnType("int");

                    b.Property<string>("CodProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodTipoPlanilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CreditoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CuentaCargoProvision")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CuentaContraPartida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Debito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DebitoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provisiona")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoCuentaContrapartida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodPartidaDetalle");

                    b.HasIndex("CodPartida");

                    b.ToTable("PartidaDetalle");
                });

            modelBuilder.Entity("PayWeb.Models.Pay_Pepe.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime");

                    b.Property<string>("Identidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("UsuarioModifica")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PayPepe_Usuarios");
                });

            modelBuilder.Entity("PayWeb.Models.Permiso", b =>
                {
                    b.Property<string>("CodEmpresa")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodPersonal")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Concepto")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("Horas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Migrado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("fecha_Actualizacion")
                        .HasColumnType("Datetime");

                    b.Property<string>("tipoPermiso")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("usuario_Actualizacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("usuario_Creacion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CodEmpresa", "CodPersonal", "Fecha", "Concepto");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("PayWeb.Models.SatelitesModel", b =>
                {
                    b.Property<int>("CodSatelite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodSatelite");

                    b.ToTable("Satelites");
                });

            modelBuilder.Entity("PayWeb.Models.TurnoDetalle", b =>
                {
                    b.Property<int>("TurnoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan?>("AlmuerzoEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AlmuerzoSalida")
                        .HasColumnType("time");

                    b.Property<int>("Dia")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TurnoFinal")
                        .HasColumnType("time");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TurnoInicio")
                        .HasColumnType("time");

                    b.HasKey("TurnoDetalleId");

                    b.ToTable("TurnoDetalle");
                });

            modelBuilder.Entity("PayWeb.Models.ControlPartidas", b =>
                {
                    b.HasOne("PayWeb.Models.Factor", "Factor")
                        .WithMany()
                        .HasForeignKey("CodFactor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factor");
                });

            modelBuilder.Entity("PayWeb.Models.ControlPlanillasMigradas", b =>
                {
                    b.HasOne("PayWeb.Models.SatelitesModel", "Satelites")
                        .WithMany()
                        .HasForeignKey("CodSatelite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Satelites");
                });

            modelBuilder.Entity("PayWeb.Models.FactorDetalle", b =>
                {
                    b.HasOne("PayWeb.Models.Factor", "Factor")
                        .WithMany()
                        .HasForeignKey("CodFactor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factor");
                });

            modelBuilder.Entity("PayWeb.Models.PartidaDetalle", b =>
                {
                    b.HasOne("PayWeb.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("CodPartida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partida");
                });
#pragma warning restore 612, 618
        }
    }
}
