// <auto-generated />
using CRM.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Migrations.Gira
{
    [DbContext(typeof(GiraContext))]
    [Migration("20260318140610_CostCenterAccountAndExpenseCC")]
    partial class CostCenterAccountAndExpenseCC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.CostCenterAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CostCenterCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("CostCenterAccount", "Gira");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("IdExpenseType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDescriptionRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImageRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvoiceRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TaxGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VendAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdExpenseType");

                    b.ToTable("ExpenseCategory", "Gira");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseCostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCostCenterAccount")
                        .HasColumnType("int");

                    b.Property<int>("IdExpenseCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdExpenseType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCostCenterAccount");

                    b.HasIndex("IdExpenseCategory");

                    b.HasIndex("IdExpenseType");

                    b.ToTable("ExpenseCostCenter", "Gira");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ExpensesType", "Gira");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseCategory", b =>
                {
                    b.HasOne("CRM.Features.Gira.ExpensesSettings.ExpenseType", "ExpenseType")
                        .WithMany("ExpensesCategories")
                        .HasForeignKey("IdExpenseType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseCostCenter", b =>
                {
                    b.HasOne("CRM.Features.Gira.ExpensesSettings.CostCenterAccount", "CostCenterAccount")
                        .WithMany("ExpensesCostCenters")
                        .HasForeignKey("IdCostCenterAccount")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CRM.Features.Gira.ExpensesSettings.ExpenseCategory", "ExpenseCategory")
                        .WithMany("ExpensesCostCenters")
                        .HasForeignKey("IdExpenseCategory")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CRM.Features.Gira.ExpensesSettings.ExpenseType", "ExpenseType")
                        .WithMany("ExpensesCostCenters")
                        .HasForeignKey("IdExpenseType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CostCenterAccount");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.CostCenterAccount", b =>
                {
                    b.Navigation("ExpensesCostCenters");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseCategory", b =>
                {
                    b.Navigation("ExpensesCostCenters");
                });

            modelBuilder.Entity("CRM.Features.Gira.ExpensesSettings.ExpenseType", b =>
                {
                    b.Navigation("ExpensesCategories");

                    b.Navigation("ExpensesCostCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
